/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jankenpoo;

import java.util.List;

/**
 *
 * @author sroma
 */
public class VistaPrincipal extends javax.swing.JFrame implements IVista{

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        PIEDRA.setActionCommand("PIEDRA");
        PAPEL.setActionCommand("PAPEL");
        TIJERA.setActionCommand("TIJERA");
        
        PIEDRA2.setActionCommand("PIEDRA");
        PAPEL2.setActionCommand("PAPEL");
        TIJERA2.setActionCommand("TIJERA");
        
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        iniciarJuego = new javax.swing.JButton();
        Partida1 = new javax.swing.JButton();
        Partida2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nomJ1 = new javax.swing.JLabel();
        nomJ2 = new javax.swing.JLabel();
        Jugar1 = new javax.swing.JButton();
        Jugar2 = new javax.swing.JButton();
        PIEDRA = new javax.swing.JRadioButton();
        PAPEL = new javax.swing.JRadioButton();
        TIJERA = new javax.swing.JRadioButton();
        PIEDRA2 = new javax.swing.JRadioButton();
        PAPEL2 = new javax.swing.JRadioButton();
        TIJERA2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTextArea();
        finalizarPartida = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarJuego.setBackground(new java.awt.Color(0, 0, 0));
        iniciarJuego.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iniciarJuego.setForeground(new java.awt.Color(255, 255, 255));
        iniciarJuego.setText("Iniciar Juego");
        jPanel2.add(iniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 76, -1, -1));

        Partida1.setBackground(new java.awt.Color(0, 0, 0));
        Partida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Partida1.setForeground(new java.awt.Color(255, 255, 255));
        Partida1.setText("Jugador 1 VS Compu");
        jPanel2.add(Partida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, -1, -1));

        Partida2.setBackground(new java.awt.Color(0, 0, 0));
        Partida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Partida2.setForeground(new java.awt.Color(255, 255, 255));
        Partida2.setText("Jugador 1 VS Jugador 2");
        jPanel2.add(Partida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 269, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 24, 490));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("JANKENPO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        nomJ1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(nomJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 110, 30));

        nomJ2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(nomJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, 30));

        Jugar1.setBackground(new java.awt.Color(0, 0, 0));
        Jugar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Jugar1.setForeground(new java.awt.Color(255, 255, 255));
        Jugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-play.png"))); // NOI18N
        Jugar1.setText("Jugar");
        jPanel2.add(Jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, -1));

        Jugar2.setBackground(new java.awt.Color(0, 0, 0));
        Jugar2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Jugar2.setForeground(new java.awt.Color(255, 255, 255));
        Jugar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-play.png"))); // NOI18N
        Jugar2.setText("JUGAR");
        jPanel2.add(Jugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        buttonGroup1.add(PIEDRA);
        PIEDRA.setText("PIEDRA");
        jPanel2.add(PIEDRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        buttonGroup1.add(PAPEL);
        PAPEL.setText("PAPEL");
        jPanel2.add(PAPEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        buttonGroup1.add(TIJERA);
        TIJERA.setText("TIJERA");
        jPanel2.add(TIJERA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        buttonGroup2.add(PIEDRA2);
        PIEDRA2.setText("PIEDRA");
        PIEDRA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIEDRA2ActionPerformed(evt);
            }
        });
        jPanel2.add(PIEDRA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        buttonGroup2.add(PAPEL2);
        PAPEL2.setText("PAPEL");
        jPanel2.add(PAPEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        buttonGroup2.add(TIJERA2);
        TIJERA2.setText("TIJERA");
        jPanel2.add(TIJERA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        tabla.setColumns(20);
        tabla.setRows(5);
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 540, 240));

        finalizarPartida.setBackground(new java.awt.Color(0, 0, 0));
        finalizarPartida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        finalizarPartida.setForeground(new java.awt.Color(255, 255, 255));
        finalizarPartida.setText("Finalizar");
        jPanel2.add(finalizarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PIEDRA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIEDRA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIEDRA2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }
    public void setPresentador(Presentador p) {
        iniciarJuego.addActionListener(p);
        recuperar.addActionListener(p);
        finalizarPartida.addActionListener(p);
        Jugar1.addActionListener(p);
        Jugar2.addActionListener(p);
        PIEDRA.addActionListener(p);
        PAPEL.addActionListener(p);
        TIJERA.addActionListener(p);
        PIEDRA2.addActionListener(p);
        PAPEL2.addActionListener(p);
        TIJERA2.addActionListener(p);
        Partida1.addActionListener(p);
        Partida2.addActionListener(p);

    }

    @Override
    public void iniciar() {
        pack();// coloca los componentes
        setLocationRelativeTo(null);// centra la ventana en la pantalla
        setVisible(true);
        Jugar1.setVisible(false);
        Jugar2.setVisible(false);
        
        nomJ1.setVisible(false);
        nomJ2.setVisible(false);

    }

    
    @Override
    public void setSalida(List<String> partidas) {
       tabla.setText("");
        for (String s : partidas) {
            tabla.append(s);
        }
    }

    
     public javax.swing.JButton getIniciarJuego() {
        return iniciarJuego;
    }

    @Override
    public String Partida1() {
        Jugar2.setVisible(true);
        Jugar1.setVisible(false);
       nomJ1.setVisible(true);
        nomJ2.setVisible(true);
       return Partida1.getText();
    }

    @Override
    public String Partida2() {
        Jugar1.setVisible(true);
        Jugar2.setVisible(false);
        nomJ1.setVisible(true);
       nomJ2.setVisible(true);
       return Partida2.getText();
    }

@Override
    public String getElemento1() {
        return buttonGroup1.getSelection().getActionCommand();
    }

    @Override
    public String getElemento2() {
        return buttonGroup2.getSelection().getActionCommand();
    }

    @Override
    public String codigo() {
       return "P0001"; 
    }

    @Override
    public void Jugadores(String J1,String J2) {
   nomJ1.setText(J1);
   nomJ2.setText(J2);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jugar1;
    public javax.swing.JButton Jugar2;
    private javax.swing.JRadioButton PAPEL;
    private javax.swing.JRadioButton PAPEL2;
    private javax.swing.JRadioButton PIEDRA;
    private javax.swing.JRadioButton PIEDRA2;
    public javax.swing.JButton Partida1;
    public javax.swing.JButton Partida2;
    private javax.swing.JRadioButton TIJERA;
    private javax.swing.JRadioButton TIJERA2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton finalizarPartida;
    public javax.swing.JButton iniciarJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomJ1;
    private javax.swing.JLabel nomJ2;
    private javax.swing.JTextArea tabla;
    // End of variables declaration//GEN-END:variables
}
